"use client"; // Marks this component as a client-side component for Next.js

import { useRouter } from "next/navigation"; // Provides navigation functionality

import React, { useState, useEffect } from "react"; // React library for building UI and managing state
import { motion } from "framer-motion"; // Animation library for React
import { containerVariants, itemVariants } from "@/lib/constant"; // Animation variants for motion components
import { Button } from "@/components/ui/button"; // Reusable button component
import { ChevronLeft, Loader2, RotateCcw } from "lucide-react"; // Icons for UI
import { Input } from "@/components/ui/input"; // Reusable input component
import useCreativeAiStore from "@/store/useCreativeAiStore"; // Zustand store for managing AI-related state

import { v4 as uuidv4 } from "uuid";

import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"; // Reusable select dropdown components
import CardList from "../CardList"; // Component to display a list of cards
import usePromptStore from "@/store/usePrompStore"; // Zustand store for managing prompt-related state
import RecentPrompt from "./RecentPrompt"; // Component to display recent prompts
import { toast } from "sonner"; // Library for displaying toast notifications
import { generateCreativePrompt } from "@/actions/openai"; // Function to generate AI prompts using OpenAI
import { OutlineCard } from "@/lib/types";
import { createProject } from "@/actions/project";
import { useSlideStore } from "@/store/useSlideStore";

type Props = {
  onBack: () => void; // Callback function for handling the back button
};

const CreateAI = ({ onBack }: Props) => {
  const router = useRouter(); // Provides navigation functionality
  const [editingCard, setEditingCard] = useState<string | null>(null); // State for tracking the card being edited
  const [isGeneratingCard, setisGeneratingCard] = useState(false); // State for tracking whether a card is being generated
  const [selectedCard, setSelectedCard] = useState<string | null>(null); // State for tracking the selected card
  const [editText, setEditText] = useState(""); // State for tracking the text being edited
  const { prompts, addPrompts } = usePromptStore(); // Zustand store for managing prompts
  const { setProject } = useSlideStore();
  const {
    currentAiPrompt, // Current AI prompt entered by the user
    setCurrentAiPrompt, // Function to update the current AI prompt
    outlines, // List of outlines generated by the AI
    resetOutlines, // Function to reset the outlines
    addOutline, // Function to add a single outline
    addMultipleOutline, // Function to add multiple outlines
  } = useCreativeAiStore();
  const [noOfCards, setNoofCards] = useState(0); // State for tracking the number of cards to display

  // Function to generate an outline based on the current AI prompt
  const generateOutline = async () => {
    if (currentAiPrompt === "") {
      // Show an error if no prompt is entered
      toast.error("Error", {
        description: "Please enter a prompt to generate an outline.",
      });
      return;
    }
    setisGeneratingCard(true); // Set loading state
    const res = await generateCreativePrompt(currentAiPrompt); // Call the OpenAI API to generate the outline
    if (res.status === 200 && res.data?.outlines) {
      const cardsData: OutlineCard[] = [];
      res.data?.outlines.map((outline: string, idx: number) => {
        const newCard = {
          id: uuidv4(),
          title: outline,
          order: idx + 1,
        };
        cardsData.push(newCard);
      });
      addMultipleOutline(cardsData);
      setNoofCards(cardsData.length);
      toast.success("Succes", {
        description: "Outline generated successfully",
      });
    } else {
      console.log(res);
      toast.error("Error", {
        description: "Failed to  generated outline. Please try again.",
      });
    }
    setisGeneratingCard(false);
  };

  // Function to handle the back button click
  const handelBack = () => {
    onBack(); // Call the parent component's back function
  };

  // Function to reset all card-related states
  const resetCards = () => {
    setEditingCard(null); // Clear the editing card
    setSelectedCard(null); // Clear the selected card
    setEditText(""); // Clear the edit text
    setCurrentAiPrompt(""); // Clear the current AI prompt
    resetOutlines(); // Reset the outlines
  };

  useEffect(() => {
    setNoofCards(outlines.length);
  }, [outlines.length]);

  // Placeholder function for generating cards
  const handelGenerate = async () => {
    setisGeneratingCard(true);
    if (outlines.length === 0) {
      toast.error("Error", {
        description: "Please add at least one card to generate slides",
      });
      return;
    }
    try {
      const res = await createProject(
        currentAiPrompt,
        outlines.slice(0, noOfCards)
      );
      if (res.status !== 200 || !res.data) {
        throw new Error("Unable to create project");
      }
      router.push(`/presentation/${res.data.id}/select-theme`);
      setProject(res.data);

      addPrompts({
        id: uuidv4(),
        title: currentAiPrompt || outlines?.[0]?.title,
        outlines: outlines,
        createdAt: new Date().toISOString(),
      });

      toast.success("Succes", {
        description: "Project Created successfully",
      });
      setCurrentAiPrompt("");
      resetOutlines();
    } catch (error) {
      console.log(error);
      toast.error("Error", {
        description: "Failed to  generated outline. Please try again.",
      });
    } finally {
      setisGeneratingCard(false);
    }
  };

  return (
    <motion.div
      className="space-y-6 w-full max-w-4xl mx-auto px-4 sm:px-6 lg:px-8" // Styling for the container
      variants={containerVariants} // Animation variants for the container
      initial="hidden" // Initial animation state
      animate="visible" // Final animation state
    >
      {/* Back Button */}
      <Button onClick={handelBack} variant={"outline"} className="mb-4">
        <ChevronLeft className="mr-2 h-4 w-4 " /> {/* Back icon */}
        Back
      </Button>

      {/* Header Section */}
      <motion.div variants={itemVariants} className="text-center space-y-2 ">
        <h1 className="text-4xl font-bold text-primary">
          Generate with <span className="text-vivid">Present AI</span>
        </h1>
        <p className="text-secondary">What would you like to create today?</p>
      </motion.div>

      {/* Input Section */}
      <motion.div
        className="bg-primary/10 p-4 rounded-xl"
        variants={itemVariants}
      >
        <div className="flex flex-col sm:flex-row justify-between gap-3 items-center rounded-xl">
          {/* Input for AI Prompt */}
          <Input
            placeholder="Enter Prompt and add to the cards..."
            className="text-base sm:text-xl border-0 focus-visible:ring-0 shadow-none p-0 bg-transparent flex-grow"
            value={currentAiPrompt} // Bind input value to state
            onChange={(e) => setCurrentAiPrompt(e.target.value)} // Update state on input change
            required
          />
          <div className="flex items-center gap-3">
            {/* Dropdown for Selecting Number of Cards */}
            <Select
              value={noOfCards.toString()} // Bind dropdown value to state
              onValueChange={(value) => setNoofCards(parseInt(value))} // Update state on selection
            >
              <SelectTrigger className="w-fit gap-2 font-semibold shadow-xl">
                <SelectValue placeholder="Select number of cards" />
              </SelectTrigger>
              <SelectContent className="w-fit">
                {outlines.length === 0 ? (
                  <SelectItem value="0" className="font-semibold">
                    No Cards
                  </SelectItem>
                ) : (
                  Array.from(
                    { length: outlines.length },
                    (_, idx) => idx + 1
                  ).map((num) => (
                    <SelectItem
                      key={num}
                      value={num.toString()}
                      className="font-semibold"
                    >
                      {num}
                      {num == 1 ? "Card" : "Cards"}
                    </SelectItem>
                  ))
                )}
              </SelectContent>
            </Select>

            {/* Reset Button */}
            <Button
              variant={"destructive"}
              onClick={resetCards}
              size={"icon"}
              aria-label="Reset Cards"
            >
              <RotateCcw className="h-4 w-4" /> {/* Reset icon */}
            </Button>
          </div>
        </div>
      </motion.div>

      {/* Generate Outline Button */}
      <div className="w-full flex justify-center items-center">
        <Button
          className="font-medium text-lg flex gap-2 items-center"
          onClick={generateOutline} // Call the generate outline function
          disabled={isGeneratingCard} // Disable button while generating
        >
          {isGeneratingCard ? (
            <>
              <Loader2 className="animate-spin mr-2" /> {/* Loading spinner */}
              Generating...
            </>
          ) : (
            "Generate Outline"
          )}
        </Button>
      </div>

      {/* Card List Section */}
      <CardList
        outlines={outlines} // Pass outlines to the CardList component
        addOutline={addOutline} // Pass function to add a single outline
        addMultipleOutlines={addMultipleOutline} // Pass function to add multiple outlines
        editText={editText} // Pass edit text state
        editingCard={editingCard} // Pass editing card state
        selectedCard={selectedCard} // Pass selected card state
        onEditChange={setEditText} // Pass function to update edit text
        onCardSelect={setSelectedCard} // Pass function to update selected card
        setEditText={setEditText} // Pass function to update edit text
        setEditingCard={setEditingCard} // Pass function to update editing card
        setSelectedCard={setSelectedCard} // Pass function to update selected card
        onCardDoubleClick={(id, title) => {
          setEditingCard(id); // Set the card being edited
          setEditText(title); // Set the text being edited
        }}
      />

      {/* Generate Button */}
      {outlines.length > 0 && (
        <Button
          className="w-full"
          onClick={handelGenerate} // Placeholder function for generating cards
          disabled={isGeneratingCard} // Disable button while generating
        >
          {isGeneratingCard ? (
            <>
              <Loader2 className="animate-spin mr-2" /> {/* Loading spinner */}
              Generating...
            </>
          ) : (
            "Generate"
          )}
        </Button>
      )}

      {/* Recent Prompts Section */}
      {prompts?.length > 0 && <RecentPrompt />}
    </motion.div>
  );
};

export default CreateAI; // Export the CreateAI component
