import React from "react";
import { Globe } from "lucide-react";

function NotFound() {
  return (
    <div className="flex flex-col min-h-[70vh] w-full justify-center items-center gap-12">
      <Globe size={100} />
      <div className="flex flex-col items-center justify-center text-center">
        <p className="text-3xl font-semibold text-primary">
          Nothing to see here
        </p>
        <p className="text-base font-normal text-secondary">
          So there is a random image generated by
          <span className="text-vivid">PresentAI</span>
        </p>
      </div>
    </div>
  );
}

export default NotFound;
